# Generated by Django 3.2.22 on 2023-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
